deployment:
  tasks:
    - export DEPLOYPATH=/home/java2779/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp global.css $DEPLOYPATH
    - /bin/cp -r src $DEPLOYPATH
